import k from"node:fs";import f from"upath";const b=/\r\n?|\n/g,E=e=>{const r=e.split(`
`),i=r.reduce((l,s)=>{for(let n=0;n<s.length;n++)if(s[n]!==" "&&s[n]!=="	")return Math.min(n,l);return l},1/0);return i<1/0?r.map(l=>l.slice(i)).join(`
`):e},S=[/^\/\/ ?#?((?:end)?region) ([\w*-]+)$/,/^\/\* ?#((?:end)?region) ([\w*-]+) ?\*\/$/,/^#pragma ((?:end)?region) ([\w*-]+)$/,/^<!-- #?((?:end)?region) ([\w*-]+) -->$/,/^#((?:End )Region) ([\w*-]+)$/,/^::#((?:end)region) ([\w*-]+)$/,/^# ?((?:end)?region) ([\w*-]+)$/],I=/^( *)<!-{2,}\s*@include:\s*([^<>|:"*?]+(?:\.[a-z0-9]+))(?:#([\w-]+))?(?:\{(\d+)?-(\d+)?\})?\s*-{2,}>\s*$/gm,F=/^( *)@include:\s*([^<>|:"*?]+(?:\.[a-z0-9]+))(?:#([\w-]+))?(?:\{(\d+)?-(\d+)?\})?\s*$/gm,$=(e,r,i,l=!1)=>{const[s,n,t]=r.exec(e.trim())||[];return!!(s&&n&&t===i&&n.match(l?/^[Ee]nd ?[rR]egion$/:/^[rR]egion$/))},y=(e,r)=>{let i=null,l=-1;for(const[s,n]of e.entries())if(i===null){for(const t of S)if($(n,t,r)){l=s+1,i=t;break}}else if($(n,i,r,!0))return{lineStart:l,lineEnd:s};return null},w=(e,{cwd:r,includedFiles:i,resolvedPath:l})=>{const{filePath:s}=e;let n=s;if(!f.isAbsolute(s)){if(!r)return console.error(`[@mdit/plugin-include]: Error when resolving path: ${s}`),`
Error when resolving path
`;n=f.resolve(r,s)}if(i.push(n),!k.existsSync(n))return console.error(`[@mdit/plugin-include]: ${n} not found`),`
File not found
`;const t=k.readFileSync(n).toString().replace(b,`
`).split(`
`);let u=[];if("region"in e){const d=y(t,e.region);d&&(u=t.slice(d.lineStart,d.lineEnd))}else{const{lineStart:d,lineEnd:o}=e;if(d)u=t.slice(d-1,o);else if(t[0]==="---"){const c=t.findIndex((p,a)=>a!==0&&p==="---");u=t.slice(Math.max(c+1,1),o)}else u=t.slice(0,o)}if(l&&n.endsWith(".md")){const d=f.dirname(n);u.unshift(`@include-push(${d})`),u.push("@include-pop()")}return E(u.join(`
`).replace(/\n?$/,`
`))},v=(e,r,{cwd:i,includedFiles:l})=>e.replace(r.useComment?I:F,(s,n,t,u,d,o)=>{const c=r.resolvePath(t,i),p=r.resolveImagePath||r.resolveLinkPath,a=w({filePath:c,...u?{region:u}:{...d?{lineStart:Number(d)}:{},...o?{lineEnd:Number(o)}:{}}},{cwd:i,includedFiles:l,resolvedPath:p});return(r.deep&&c.endsWith(".md")?v(a,r,{cwd:f.isAbsolute(c)?f.dirname(c):i?f.resolve(i,f.dirname(c)):null,includedFiles:l}):a).split(`
`).map(h=>n+h).join(`
`)}),A=/^@include-push\(([^)]*?)\)$/,x=(e,r,i,l)=>{const s=e.bMarks[r]+e.tShift[r],n=e.eMarks[r];if(e.src.charAt(s)!=="@")return!1;const t=e.src.slice(s,n);if(t.startsWith("@include-push")){const u=t.match(A);if(u){if(l)return!0;const[,d]=u;e.line=r+1;const o=e.push("include_push","",0);return o.map=[r,e.line],o.info=d,o.markup="include_push",!0}}return!1},M=(e,r,i,l)=>{const s=e.bMarks[r]+e.tShift[r],n=e.eMarks[r];if(e.src.charAt(s)!=="@")return!1;if(e.src.slice(s,n)==="@include-pop()"){if(l)return!0;e.line=r+1;const t=e.push("include_pop","",0);return t.map=[r,e.line],t.markup="include_pop",!0}return!1},_=(e,r,i,l)=>{const s=r.attrIndex(e),n=r.attrs?.[s][1];if(n?.startsWith(".")&&Array.isArray(l)){const{length:t}=l;if(t){const u=f.relative(f.dirname(i),l[t-1]),d=f.join(u,n);r.attrs[s][1]=d[0]==="."?d:`./${d}`}}},W=(e,r)=>{const{currentPath:i,resolvePath:l=o=>o,deep:s=!1,resolveLinkPath:n=!0,resolveImagePath:t=!0,useComment:u=!0}=r||{};if(typeof i!="function")return console.error('[@mdit/plugin-include]: "currentPath" is required');const d=o=>{const c=o.env,p=c.includedFiles||(c.includedFiles=[]),a=i(c);o.src=v(o.src,{currentPath:i,resolvePath:l,deep:s,resolveLinkPath:n,resolveImagePath:t,useComment:u},{cwd:a?f.dirname(a):null,includedFiles:p})};if(e.core.ruler.after("normalize","md_import",d),t||n){if(e.block.ruler.before("table","md_include_push",x,{alt:["paragraph","reference","blockquote","list"]}),e.block.ruler.before("table","md_include_pop",M,{alt:["paragraph","reference","blockquote","list"]}),e.renderer.rules.include_push=(o,c,p,a)=>{const h=o[c];return(a.includedPaths??=[]).push(h.info),""},e.renderer.rules.include_pop=(o,c,p,a)=>{const h=a.includedPaths;return Array.isArray(h)?h.pop():console.error("[@mdit/plugin-include]: include_pop failed, no include_push."),""},t){const o=e.renderer.rules.image;e.renderer.rules.image=(c,p,a,h,m)=>{const P=c[p],g=i(h);return g&&_("src",P,g,h.includedPaths),o(c,p,a,h,m)}}if(n){const o=e.renderer.rules.link_open??((c,p,a,h,m)=>m.renderToken(c,p,a));e.renderer.rules.link_open=(c,p,a,h,m)=>{const P=c[p],g=i(h);return g&&_("href",P,g,h.includedPaths),o(c,p,a,h,m)}}}};export{w as handleInclude,W as include,v as resolveInclude};
//# sourceMappingURL=index.mjs.map
