"use strict";var k=require("node:fs"),f=require("upath");const b=/\r\n?|\n/g,I=e=>{const r=e.split(`
`),t=r.reduce((l,s)=>{for(let n=0;n<s.length;n++)if(s[n]!==" "&&s[n]!=="	")return Math.min(n,l);return l},1/0);return t<1/0?r.map(l=>l.slice(t)).join(`
`):e},E=[/^\/\/ ?#?((?:end)?region) ([\w*-]+)$/,/^\/\* ?#((?:end)?region) ([\w*-]+) ?\*\/$/,/^#pragma ((?:end)?region) ([\w*-]+)$/,/^<!-- #?((?:end)?region) ([\w*-]+) -->$/,/^#((?:End )Region) ([\w*-]+)$/,/^::#((?:end)region) ([\w*-]+)$/,/^# ?((?:end)?region) ([\w*-]+)$/],S=/^( *)<!-{2,}\s*@include:\s*([^<>|:"*?]+(?:\.[a-z0-9]+))(?:#([\w-]+))?(?:\{(\d+)?-(\d+)?\})?\s*-{2,}>\s*$/gm,F=/^( *)@include:\s*([^<>|:"*?]+(?:\.[a-z0-9]+))(?:#([\w-]+))?(?:\{(\d+)?-(\d+)?\})?\s*$/gm,$=(e,r,t,l=!1)=>{const[s,n,i]=r.exec(e.trim())||[];return!!(s&&n&&i===t&&n.match(l?/^[Ee]nd ?[rR]egion$/:/^[rR]egion$/))},y=(e,r)=>{let t=null,l=-1;for(const[s,n]of e.entries())if(t===null){for(const i of E)if($(n,i,r)){l=s+1,t=i;break}}else if($(n,t,r,!0))return{lineStart:l,lineEnd:s};return null},w=(e,{cwd:r,includedFiles:t,resolvedPath:l})=>{const{filePath:s}=e;let n=s;if(!f.isAbsolute(s)){if(!r)return console.error(`[@mdit/plugin-include]: Error when resolving path: ${s}`),`
Error when resolving path
`;n=f.resolve(r,s)}if(t.push(n),!k.existsSync(n))return console.error(`[@mdit/plugin-include]: ${n} not found`),`
File not found
`;const i=k.readFileSync(n).toString().replace(b,`
`).split(`
`);let u=[];if("region"in e){const d=y(i,e.region);d&&(u=i.slice(d.lineStart,d.lineEnd))}else{const{lineStart:d,lineEnd:o}=e;if(d)u=i.slice(d-1,o);else if(i[0]==="---"){const c=i.findIndex((p,a)=>a!==0&&p==="---");u=i.slice(Math.max(c+1,1),o)}else u=i.slice(0,o)}if(l&&n.endsWith(".md")){const d=f.dirname(n);u.unshift(`@include-push(${d})`),u.push("@include-pop()")}return I(u.join(`
`).replace(/\n?$/,`
`))},P=(e,r,{cwd:t,includedFiles:l})=>e.replace(r.useComment?S:F,(s,n,i,u,d,o)=>{const c=r.resolvePath(i,t),p=r.resolveImagePath||r.resolveLinkPath,a=w({filePath:c,...u?{region:u}:{...d?{lineStart:Number(d)}:{},...o?{lineEnd:Number(o)}:{}}},{cwd:t,includedFiles:l,resolvedPath:p});return(r.deep&&c.endsWith(".md")?P(a,r,{cwd:f.isAbsolute(c)?f.dirname(c):t?f.resolve(t,f.dirname(c)):null,includedFiles:l}):a).split(`
`).map(h=>n+h).join(`
`)}),A=/^@include-push\(([^)]*?)\)$/,x=(e,r,t,l)=>{const s=e.bMarks[r]+e.tShift[r],n=e.eMarks[r];if(e.src.charAt(s)!=="@")return!1;const i=e.src.slice(s,n);if(i.startsWith("@include-push")){const u=i.match(A);if(u){if(l)return!0;const[,d]=u;e.line=r+1;const o=e.push("include_push","",0);return o.map=[r,e.line],o.info=d,o.markup="include_push",!0}}return!1},M=(e,r,t,l)=>{const s=e.bMarks[r]+e.tShift[r],n=e.eMarks[r];if(e.src.charAt(s)!=="@")return!1;if(e.src.slice(s,n)==="@include-pop()"){if(l)return!0;e.line=r+1;const i=e.push("include_pop","",0);return i.map=[r,e.line],i.markup="include_pop",!0}return!1},_=(e,r,t,l)=>{const s=r.attrIndex(e),n=r.attrs?.[s][1];if(n?.startsWith(".")&&Array.isArray(l)){const{length:i}=l;if(i){const u=f.relative(f.dirname(t),l[i-1]),d=f.join(u,n);r.attrs[s][1]=d[0]==="."?d:`./${d}`}}},q=(e,r)=>{const{currentPath:t,resolvePath:l=o=>o,deep:s=!1,resolveLinkPath:n=!0,resolveImagePath:i=!0,useComment:u=!0}=r||{};if(typeof t!="function")return console.error('[@mdit/plugin-include]: "currentPath" is required');const d=o=>{const c=o.env,p=c.includedFiles||(c.includedFiles=[]),a=t(c);o.src=P(o.src,{currentPath:t,resolvePath:l,deep:s,resolveLinkPath:n,resolveImagePath:i,useComment:u},{cwd:a?f.dirname(a):null,includedFiles:p})};if(e.core.ruler.after("normalize","md_import",d),i||n){if(e.block.ruler.before("table","md_include_push",x,{alt:["paragraph","reference","blockquote","list"]}),e.block.ruler.before("table","md_include_pop",M,{alt:["paragraph","reference","blockquote","list"]}),e.renderer.rules.include_push=(o,c,p,a)=>{const h=o[c];return(a.includedPaths??=[]).push(h.info),""},e.renderer.rules.include_pop=(o,c,p,a)=>{const h=a.includedPaths;return Array.isArray(h)?h.pop():console.error("[@mdit/plugin-include]: include_pop failed, no include_push."),""},i){const o=e.renderer.rules.image;e.renderer.rules.image=(c,p,a,h,m)=>{const v=c[p],g=t(h);return g&&_("src",v,g,h.includedPaths),o(c,p,a,h,m)}}if(n){const o=e.renderer.rules.link_open??((c,p,a,h,m)=>m.renderToken(c,p,a));e.renderer.rules.link_open=(c,p,a,h,m)=>{const v=c[p],g=t(h);return g&&_("href",v,g,h.includedPaths),o(c,p,a,h,m)}}}};exports.handleInclude=w,exports.include=q,exports.resolveInclude=P;
//# sourceMappingURL=index.cjs.map
