export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"MITRE SAF Training","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"person-chalkboard"},[":md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"Guide","i":"lightbulb"},["/guide/README.md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"Features demo","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"Disabling layout and features","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown Enhance","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"Page Config","i":"file","O":1},[":md"]],
  ["v-2ae58894","/installation/LinuxInstall.html",{"y":"a","t":"Installing InSpec on Linux","i":"page"},[":md"]],
  ["v-59a19ede","/installation/MacInstall.html",{"y":"a","t":"Installing InSpec on MacOS","i":"page"},[":md"]],
  ["v-08a5d2dc","/installation/",{"y":"a","t":"Installing InSpec On Your Machine","i":"page"},["/installation/README.md"]],
  ["v-4f4ac476","/installation/WindowsInstall.html",{"y":"a","t":"Installing InSpec on Windows","i":"page"},[":md"]],
  ["v-255cf054","/resources/02.html",{"y":"a","t":"Codespaces Resources","i":"page"},[":md"]],
  ["v-2711c8f3","/resources/03.html",{"y":"a","t":"Training Development Docs","i":"page"},[":md"]],
  ["v-28c6a192","/resources/04.html",{"y":"a","t":"Vulcan Resources","i":"page"},[":md"]],
  ["v-7fe15663","/resources/",{"y":"a","t":"Class Resources","i":"page"},["/resources/README.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar feature","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo feature","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-2ecf6c9a","/courses/advanced/02.html",{"y":"a","t":"2. Review the Fundamentals","O":2},[":md"]],
  ["v-30844539","/courses/advanced/03.html",{"y":"a","t":"3. Practice the Fundamentals","O":3},[":md"]],
  ["v-32391dd8","/courses/advanced/04.html",{"y":"a","t":"4. Exploring InSpec Resources","O":4},[":md"]],
  ["v-33edf677","/courses/advanced/05.html",{"y":"a","t":"5. Create a Custom Resource - The Git Example","O":5},[":md"]],
  ["v-35a2cf16","/courses/advanced/06.html",{"y":"a","t":"6. Create a Custom Resource - The Docker Example","O":6},[":md"]],
  ["v-3757a7b5","/courses/advanced/07.html",{"y":"a","t":"7. Exercise - Develop your own resources","O":7},[":md"]],
  ["v-390c8054","/courses/advanced/08.html",{"y":"a","t":"8. CI/CD Pipelines","O":8},[":md"]],
  ["v-3ac158f3","/courses/advanced/09.html",{"y":"a","t":"9. GitHub Actions","O":9},[":md"]],
  ["v-604bf69d","/courses/advanced/10.html",{"y":"a","t":"10. Building Out Our Pipeline","O":10},[":md"]],
  ["v-6200cf3c","/courses/advanced/11.html",{"y":"a","t":"11. Verifying Results With The SAF CLI","O":11},[":md"]],
  ["v-63b5a7db","/courses/advanced/12.html",{"y":"a","t":"12. Next Steps","O":12},[":md"]],
  ["v-32f5f052","/courses/advanced/Appendix%20A%20-%20Writing%20Plural%20Resources.html",{"y":"a","t":"Appendix A - Writing Plural Resources","O":14},["/courses/advanced/Appendix A - Writing Plural Resources.html","/courses/advanced/Appendix A - Writing Plural Resources.md",":md"]],
  ["v-937704e2","/courses/advanced/Appendix%20B%20-%20Resource%20Examples.html",{"y":"a","t":"Appendix B - Custom Resource Examples from InSpec","O":15},["/courses/advanced/Appendix B - Resource Examples.html","/courses/advanced/Appendix B - Resource Examples.md",":md"]],
  ["v-f978fcb6","/courses/advanced/Appendix%20C%20-%20Adding%20Your%20Resource%20to%20InSpec.html",{"y":"a","t":"Appendix C - Adding Your Resource to InSpec","O":16},["/courses/advanced/Appendix C - Adding Your Resource to InSpec.html","/courses/advanced/Appendix C - Adding Your Resource to InSpec.md",":md"]],
  ["v-4faaa59d","/courses/advanced/Appendix%20D%20-%20Example%20Pipeline%20for%20Validating%20an%20InSpec%20Profile.html",{"y":"a","t":"Appendix D - Example Pipeline for Validating an InSpec Profile","O":17},["/courses/advanced/Appendix D - Example Pipeline for Validating an InSpec Profile.html","/courses/advanced/Appendix D - Example Pipeline for Validating an InSpec Profile.md",":md"]],
  ["v-b1912590","/courses/advanced/Appendix%20E%20-%20More%20Resource%20Examples.html",{"y":"a","t":"Appendix B - More Resource Examples","O":18},["/courses/advanced/Appendix E - More Resource Examples.html","/courses/advanced/Appendix E - More Resource Examples.md",":md"]],
  ["v-0cb10646","/courses/advanced/",{"y":"a","t":"InSpec Advanced Profile Development","s":"Advanced Profile Development"},["/courses/advanced/README.md"]],
  ["v-23e7d8ca","/courses/beginner/02.html",{"y":"a","t":"2. What is an InSpec Profile?","O":2},[":md"]],
  ["v-259cb169","/courses/beginner/03.html",{"y":"a","t":"3. Study an InSpec Profile - NGINX Example","O":3},[":md"]],
  ["v-27518a08","/courses/beginner/04.html",{"y":"a","t":"4. How to Get Started - InSpec Commands & Docs","O":4},[":md"]],
  ["v-290662a7","/courses/beginner/05.html",{"y":"a","t":"5. Writing InSpec Controls","O":5},[":md"]],
  ["v-2abb3b46","/courses/beginner/06.html",{"y":"a","t":"6. Inputs in InSpec","O":6},[":md"]],
  ["v-2c7013e5","/courses/beginner/07.html",{"y":"a","t":"7. InSpec Control Enhancements","O":7},[":md"]],
  ["v-2e24ec84","/courses/beginner/08.html",{"y":"a","t":"8. Generating InSpec Results","O":8},[":md"]],
  ["v-2fd9c523","/courses/beginner/09.html",{"y":"a","t":"9. Viewing and Analyzing Results","O":9},[":md"]],
  ["v-556462cd","/courses/beginner/10.html",{"y":"a","t":"10. Profile Dependencies (Overlays)","O":10},[":md"]],
  ["v-57193b6c","/courses/beginner/11.html",{"y":"a","t":"11. From STIG to Profile","O":11},[":md"]],
  ["v-58ce140b","/courses/beginner/12.html",{"y":"a","t":"12. Put it in Practice!","O":12},[":md"]],
  ["v-5a82ecaa","/courses/beginner/13.html",{"y":"a","t":"13. Next Steps","O":13},[":md"]],
  ["v-2c0932a6","/courses/beginner/",{"y":"a","t":"Beginner Security Automation Developer Class","s":"Beginner Profile Development"},["/courses/beginner/README.md"]],
  ["v-709259d0","/courses/guidance/02.html",{"y":"a","t":"2. Security Guidance","O":2},[":md"]],
  ["v-7247326f","/courses/guidance/03.html",{"y":"a","t":"3. Security Technical Implementation Guides","O":3},[":md"]],
  ["v-73fc0b0e","/courses/guidance/04.html",{"y":"a","t":"4. Anatomy of a STIG","O":4},[":md"]],
  ["v-75b0e3ad","/courses/guidance/05.html",{"y":"a","t":"5. Using Vulcan","O":5},[":md"]],
  ["v-7765bc4c","/courses/guidance/06.html",{"y":"a","t":"6. Components Of a Vulcan Project","O":6},[":md"]],
  ["v-791a94eb","/courses/guidance/07.html",{"y":"a","t":"7. Editing Components","O":7},[":md"]],
  ["v-7acf6d8a","/courses/guidance/08.html",{"y":"a","t":"8. Check and Fix","O":8},[":md"]],
  ["v-7c844629","/courses/guidance/09.html",{"y":"a","t":"9. Automated InSpec Testing","O":9},[":md"]],
  ["v-bbe2385a","/courses/guidance/10.html",{"y":"a","t":"10. Peer Review","O":10},[":md"]],
  ["v-b878871c","/courses/guidance/11.html",{"y":"a","t":"11. Exporting Your Content","O":11},[":md"]],
  ["v-b50ed5de","/courses/guidance/12.html",{"y":"a","t":"12. Publishing a STIG","O":12},[":md"]],
  ["v-b1a524a0","/courses/guidance/13.html",{"y":"a","t":"13. Next Steps","O":13},[":md"]],
  ["v-a41d3f32","/courses/guidance/",{"y":"a","t":"Security Guidance Developer Class","s":"Security Guidance Development"},["/courses/guidance/README.md"]],
  ["v-76a3f766","/courses/profile-dev-test/02.html",{"y":"a","t":"Repository Organization","O":2},[":md"]],
  ["v-7858d005","/courses/profile-dev-test/03.html",{"y":"a","t":"Environment Setup","O":3},[":md"]],
  ["v-7a0da8a4","/courses/profile-dev-test/04.html",{"y":"a","t":"Test your Test Environment","O":4},[":md"]],
  ["v-7bc28143","/courses/profile-dev-test/05.html",{"y":"a","t":"AWS Testing Suite","O":5},[":md"]],
  ["v-7d7759e2","/courses/profile-dev-test/06.html",{"y":"a","t":"Docker Testing Suite","O":6},[":md"]],
  ["v-7f2c3281","/courses/profile-dev-test/07.html",{"y":"a","t":"Updating - Choosing Your Apprach","O":7},[":md"]],
  ["v-fe3de9c0","/courses/profile-dev-test/08.html",{"y":"a","t":"Secruity Benchmarks vs Traditional Software","O":8},[":md"]],
  ["v-fad43882","/courses/profile-dev-test/09.html",{"y":"a","t":"Types of Profile Updates","O":9},[":md"]],
  ["v-afbefd2e","/courses/profile-dev-test/10.html",{"y":"a","t":"Rules of the Road","O":10},[":md"]],
  ["v-ac554bf0","/courses/profile-dev-test/11.html",{"y":"a","t":"Creating a `Patch Update`","O":11},[":md"]],
  ["v-a8eb9ab2","/courses/profile-dev-test/12.html",{"y":"a","t":"Creating a `Release Update`","O":12},[":md"]],
  ["v-a581e974","/courses/profile-dev-test/13.html",{"y":"a","t":"Creating a `Major Version Update`","O":13},[":md"]],
  ["v-a2183836","/courses/profile-dev-test/14.html",{"y":"a","t":"Test Kitchen","O":14},[":md"]],
  ["v-9eae86f8","/courses/profile-dev-test/15.html",{"y":"a","t":"Test Kitchen - Create","O":15},[":md"]],
  ["v-9b44d5ba","/courses/profile-dev-test/16.html",{"y":"a","t":"Test Kitchen - Converge","O":16},[":md"]],
  ["v-97db247c","/courses/profile-dev-test/17.html",{"y":"a","t":"Test Kitchen - Validate","O":17},[":md"]],
  ["v-9471733e","/courses/profile-dev-test/18.html",{"y":"a","t":"Test Kitchen - Destroy","O":18},[":md"]],
  ["v-9107c200","/courses/profile-dev-test/19.html",{"y":"a","t":"Test Kitchen - .kitchen/ directory","O":19},[":md"]],
  ["v-45f286ac","/courses/profile-dev-test/20.html",{"y":"a","t":"Test Kitchen - `kitchen.yml` File","O":20},[":md"]],
  ["v-4288d56e","/courses/profile-dev-test/21.html",{"y":"a","t":"Test Kitchen - `kitchen.ec2.yml` File","O":21},[":md"]],
  ["v-3f1f2430","/courses/profile-dev-test/22.html",{"y":"a","t":"Test Kitchen - `kitchen.container.yml`","O":22},[":md"]],
  ["v-3bb572f2","/courses/profile-dev-test/23.html",{"y":"a","t":"GitHub Actions","O":23},[":md"]],
  ["v-384bc1b4","/courses/profile-dev-test/24.html",{"y":"a","t":"InSpec Delta - Laying the Ground for a Clean Release Branch","O":24,"s":"Delta - Prep & Setup"},[":md"]],
  ["v-34e21076","/courses/profile-dev-test/25.html",{"y":"a","t":"InSpec Delta - Making the Delta Release Branch","O":25,"s":"Delta - Making your Branch"},[":md"]],
  ["v-31785f38","/courses/profile-dev-test/26.html",{"y":"a","t":"Tips, Tricks & Troubleshooting","O":26,"s":"Tips & Troubleshooting"},[":md"]],
  ["v-2e0eadfa","/courses/profile-dev-test/27.html",{"y":"a","t":"Background & Definitions","O":27},[":md"]],
  ["v-2aa4fcbc","/courses/profile-dev-test/28.html",{"y":"a","t":"Terms & Definitions","O":28},[":md"]],
  ["v-10283f91","/courses/profile-dev-test/",{"y":"a","t":"Development & Testing InSpec Profile"},["/courses/profile-dev-test/README.md"]],
  ["v-08816f43","/courses/user/02.html",{"y":"a","t":"2. The Goal of the SAF","O":2},[":md"]],
  ["v-0a3647e2","/courses/user/03.html",{"y":"a","t":"3. What's the SAF?","O":3},[":md"]],
  ["v-0beb2081","/courses/user/04.html",{"y":"a","t":"4. Getting Started - Plan","O":4},[":md"]],
  ["v-0d9ff920","/courses/user/05.html",{"y":"a","t":"5. Validation with InSpec Profiles","O":5},[":md"]],
  ["v-0f54d1bf","/courses/user/06.html",{"y":"a","t":"6. How to Run InSpec","O":6},[":md"]],
  ["v-1109aa5e","/courses/user/07.html",{"y":"a","t":"7. Tailoring Inputs for InSpec","O":7},[":md"]],
  ["v-12be82fd","/courses/user/08.html",{"y":"a","t":"8. Running InSpec","O":8},[":md"]],
  ["v-14735b9c","/courses/user/09.html",{"y":"a","t":"9. Visualize Results - Heimdall","O":9},[":md"]],
  ["v-39fdf946","/courses/user/10.html",{"y":"a","t":"10. Harden","O":10},[":md"]],
  ["v-3bb2d1e5","/courses/user/11.html",{"y":"a","t":"11. Comparing Results","O":11},[":md"]],
  ["v-3d67aa84","/courses/user/12.html",{"y":"a","t":"12. Manual Attestations","O":12},[":md"]],
  ["v-3f1c8323","/courses/user/13.html",{"y":"a","t":"13. InSpec Exercise - RedHat","O":13},[":md"]],
  ["v-40d15bc2","/courses/user/14.html",{"y":"a","t":"14. Normalize Other Data!","O":14},[":md"]],
  ["v-42863461","/courses/user/15.html",{"y":"a","t":"15. Extra Info - Running InSpec with a Local Profile","O":15},[":md"]],
  ["v-443b0d00","/courses/user/16.html",{"y":"a","t":"16. Next Steps","O":16},[":md"]],
  ["v-6d2f3654","/courses/user/",{"y":"a","t":"SAF User Class","s":"SAF User Class"},["/courses/user/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-7e978520","/courses/",{"y":"p","t":"Courses"},[]],
]
