export const data = JSON.parse("{\"key\":\"v-0beb2081\",\"path\":\"/courses/user/04.html\",\"title\":\"4. Getting Started - Plan\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":4,\"next\":\"05.md\",\"title\":\"4. Getting Started - Plan\",\"author\":\"Aaron Lippold\",\"headerDepth\":3,\"description\":\"4. Start with Planning The SAF's main pillars are Plan, Harden, Validate, Normalize, and Visualize. First, it is necessary to plan what components will be in your system and ide...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/user/04.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"4. Getting Started - Plan\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"4. Start with Planning The SAF's main pillars are Plan, Harden, Validate, Normalize, and Visualize. First, it is necessary to plan what components will be in your system and ide...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"4. Getting Started - Plan\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"4. Start with Planning\",\"slug\":\"_4-start-with-planning\",\"link\":\"#_4-start-with-planning\",\"children\":[{\"level\":3,\"title\":\"4.1 Identify your stack of components for the system\",\"slug\":\"_4-1-identify-your-stack-of-components-for-the-system\",\"link\":\"#_4-1-identify-your-stack-of-components-for-the-system\",\"children\":[]},{\"level\":3,\"title\":\"4.2 What is the guidance?\",\"slug\":\"_4-2-what-is-the-guidance\",\"link\":\"#_4-2-what-is-the-guidance\",\"children\":[]},{\"level\":3,\"title\":\"4.3. Content libraries for software components\",\"slug\":\"_4-3-content-libraries-for-software-components\",\"link\":\"#_4-3-content-libraries-for-software-components\",\"children\":[]},{\"level\":3,\"title\":\"4.4. What if there is no content for a software component?\",\"slug\":\"_4-4-what-if-there-is-no-content-for-a-software-component\",\"link\":\"#_4-4-what-if-there-is-no-content-for-a-software-component\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.71,\"words\":513},\"filePathRelative\":\"courses/user/04.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
