export const data = JSON.parse("{\"key\":\"v-3d67aa84\",\"path\":\"/courses/user/12.html\",\"title\":\"12. Manual Attestations\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":12,\"next\":\"13.md\",\"title\":\"12. Manual Attestations\",\"author\":\"Emily Rodriguez\",\"headerDepth\":3,\"description\":\"12. Manual Attestations What about controls that cannot be automated and require manual review? You may have noticed that Heimdall displays controls in 4 statuses: Passed, Faile...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/user/12.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"12. Manual Attestations\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"12. Manual Attestations What about controls that cannot be automated and require manual review? You may have noticed that Heimdall displays controls in 4 statuses: Passed, Faile...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Emily Rodriguez\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"12. Manual Attestations\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Emily Rodriguez\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"12. Manual Attestations\",\"slug\":\"_12-manual-attestations\",\"link\":\"#_12-manual-attestations\",\"children\":[{\"level\":3,\"title\":\"12.1 Explore the Not Reviewed Controls\",\"slug\":\"_12-1-explore-the-not-reviewed-controls\",\"link\":\"#_12-1-explore-the-not-reviewed-controls\",\"children\":[]},{\"level\":3,\"title\":\"12.2 Manual Attestations Using SAF CLI\",\"slug\":\"_12-2-manual-attestations-using-saf-cli\",\"link\":\"#_12-2-manual-attestations-using-saf-cli\",\"children\":[]},{\"level\":3,\"title\":\"12.3 Get Familiar with SAF CLI\",\"slug\":\"_12-3-get-familiar-with-saf-cli\",\"link\":\"#_12-3-get-familiar-with-saf-cli\",\"children\":[]},{\"level\":3,\"title\":\"12.4 Create Manual Attestation Data\",\"slug\":\"_12-4-create-manual-attestation-data\",\"link\":\"#_12-4-create-manual-attestation-data\",\"children\":[]},{\"level\":3,\"title\":\"12.5 Apply the Manual Attestation Data\",\"slug\":\"_12-5-apply-the-manual-attestation-data\",\"link\":\"#_12-5-apply-the-manual-attestation-data\",\"children\":[]},{\"level\":3,\"title\":\"12.6 Visualize the Results - Heimdall\",\"slug\":\"_12-6-visualize-the-results-heimdall\",\"link\":\"#_12-6-visualize-the-results-heimdall\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.89,\"words\":1167},\"filePathRelative\":\"courses/user/12.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
