<template><div><h1 id="terms-definitions" tabindex="-1"><a class="header-anchor" href="#terms-definitions" aria-hidden="true">#</a> Terms &amp; Definitions</h1>
<ul>
<li><strong>Baseline</strong>: This refers to a set of relevant security controls, such as NIST 800-53 controls or Center for Internet Security Controls. These controls offer high-level security best practices, grouped into common areas of concern.</li>
<li><strong>Benchmark</strong>: This is a set of security controls tailored to a specific type of application or product. These controls are typically categorized into 'high', 'medium', and 'low' levels based on Confidentiality, Integrity, and Availability (C.I.A).</li>
<li><strong><a href="https://public.cyber.mil/stigs/cci/" target="_blank" rel="noopener noreferrer">Common Correlation Identifier<ExternalLinkIcon/></a> (CCI)</strong>: The Control Correlation Identifier (CCI) provides a standard identifier and description for each of the singular, actionable statements that comprise an IA control or IA best practice. For example: 'CCI-000366'.</li>
<li><strong>Group Title (gtitle)</strong>: This is essentially the SRG ID but is a holdover data value from the old Vulnerability Management System. For example:  'SRG-OS-000480-GPOS-00227'.</li>
<li><strong>Major Version Update</strong>: These are updates that occur when a software vendor releases a new major version of their product's STIG, e.g., RedHat releasing version 9 of Red Hat Enterprise Linux or Microsoft releasing a new major version of Windows.</li>
<li><strong>Patch Update</strong>: These are regular updates that address missing corner cases of testing for one or more benchmark requirements, or improvements to the InSpec code for a requirement. These updates result in a new patch release of the benchmark, e.g., <code v-pre>v1.12.4</code> to <code v-pre>v1.12.5</code>.</li>
<li><strong>Profile</strong>: This is a set of tests representing a STIG or a CIS Benchmark. These tests automate the validation of a system against that STIG or CIS Benchmark.</li>
<li><strong>Release Update</strong>: These are updates that occur when the STIG Benchmark owner releases an updated version of the STIG, e.g., Red Hat Enterprise Linux V1R12 to V1R13.</li>
<li><strong>Rule ID (rid)</strong>: The Rule ID has two parts separated by the <code v-pre>r</code> in the string - ('SV-230221) and (r858734_rule)'. The first part remains unique within the major version of a Benchmark document, while the latter part of the string is updated each time the 'Rule' is updated 'release to release' of the Benchmark. For example: 'SV-230221r858734_rule'.</li>
<li><strong>Security Requirements Guide (SRG)</strong>: SRG documents provide generalized security guidance in XCCDF format that applies to a 'class' of software products such as 'web server', 'operating systems', 'application servers' or 'databases'. You can find an archive of these at the DISA STIG <a href="https://public.cyber.mil/stigs/downloads/" target="_blank" rel="noopener noreferrer">Document Library<ExternalLinkIcon/></a>.</li>
<li><strong>Security Technical Implementation Guide (STIG)</strong>: This is a set of specific technical actions required to establish a certain security posture for a software product. It is based on a desired Security Requirements Guide that applies to the product's software class and function, such as operating system, web server, database, etc. You can find an archive of these at the DISA STIG <a href="https://public.cyber.mil/stigs/downloads/" target="_blank" rel="noopener noreferrer">Document Library<ExternalLinkIcon/></a>.</li>
<li><strong>SRG_ID</strong>: This is the unique identifier of the SRG requirement. These indexes, like the STIG Rule IDs, also show their parent-child relationship. For example: 'SRG-OS-000480-GPOS-00227'.</li>
<li><strong>STIG ID (stig_id)</strong>: Many testing tools and testing results tools use this ID - vs the Rule ID - to display each of the individual results of a Benchmark validation run. For example: 'RHEL-08-010000'. Examples include: DISA STIG Viewer, Nessus Audit Scans and the Open SCAP client.</li>
<li><strong>XCCDF Benchmark (XCCDF or XCCDF Benchmark)</strong>: XCCDF (Extensible Configuration Checklist Description Format) is a standard developed by NIST and DOD to provide a machine-readable XML format for creating security guidance documents and security technical implementation guides. You can find an archive of these at the DISA STIG <a href="https://public.cyber.mil/stigs/downloads/" target="_blank" rel="noopener noreferrer">Document Library<ExternalLinkIcon/></a>.</li>
</ul>
</div></template>


