export const data = JSON.parse("{\"key\":\"v-601a37d4\",\"path\":\"/courses/profile-dev-test/Repository-Organization.html\",\"title\":\"Repository Organization\",\"lang\":\"en-US\",\"frontmatter\":{\"next\":\"03.md\",\"title\":\"Repository Organization\",\"author\":\"Aaron Lippold\",\"index\":true,\"description\":\"The repository and profile are organized into two primary branches: main and TBD. The repository has a set of tags representing iterative releases of the STIG from one Benchmark...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/profile-dev-test/Repository-Organization.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Repository Organization\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"The repository and profile are organized into two primary branches: main and TBD. The repository has a set of tags representing iterative releases of the STIG from one Benchmark...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Repository Organization\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Branches\",\"slug\":\"branches\",\"link\":\"#branches\",\"children\":[{\"level\":3,\"title\":\"main branch\",\"slug\":\"main-branch\",\"link\":\"#main-branch\",\"children\":[]},{\"level\":3,\"title\":\"v{x}r{xx} branches\",\"slug\":\"v-x-r-xx-branches\",\"link\":\"#v-x-r-xx-branches\",\"children\":[]}]},{\"level\":2,\"title\":\"Releases\",\"slug\":\"releases\",\"link\":\"#releases\",\"children\":[]},{\"level\":2,\"title\":\"Tags\",\"slug\":\"tags\",\"link\":\"#tags\",\"children\":[{\"level\":3,\"title\":\"Current Tag\",\"slug\":\"current-tag\",\"link\":\"#current-tag\",\"children\":[]},{\"level\":3,\"title\":\"Major Tags\",\"slug\":\"major-tags\",\"link\":\"#major-tags\",\"children\":[]},{\"level\":3,\"title\":\"Patch Releases\",\"slug\":\"patch-releases\",\"link\":\"#patch-releases\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.45,\"words\":435},\"filePathRelative\":\"courses/profile-dev-test/Repository-Organization.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
