export const data = JSON.parse("{\"key\":\"v-23e7d8ca\",\"path\":\"/courses/beginner/02.html\",\"title\":\"2. What is an InSpec Profile?\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":2,\"next\":\"03.md\",\"title\":\"2. What is an InSpec Profile?\",\"author\":\"Aaron Lippold\",\"description\":\"Check-InHave you used InSpec before? There is no right or wrong answer. If this is your first time using InSpec, welcome! If you have used it before, welcome back. If you want m...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/02.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"2. What is an InSpec Profile?\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Check-InHave you used InSpec before? There is no right or wrong answer. If this is your first time using InSpec, welcome! If you have used it before, welcome back. If you want m...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"2. What is an InSpec Profile?\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Check-In\",\"slug\":\"check-in\",\"link\":\"#check-in\",\"children\":[]},{\"level\":2,\"title\":\"What is an InSpec Profile?\",\"slug\":\"what-is-an-inspec-profile\",\"link\":\"#what-is-an-inspec-profile\",\"children\":[{\"level\":3,\"title\":\"InSpec Profiles\",\"slug\":\"inspec-profiles\",\"link\":\"#inspec-profiles\",\"children\":[]},{\"level\":3,\"title\":\"InSpec Profile Structure\",\"slug\":\"inspec-profile-structure\",\"link\":\"#inspec-profile-structure\",\"children\":[]},{\"level\":3,\"title\":\"InSpec Controls Structure\",\"slug\":\"inspec-controls-structure\",\"link\":\"#inspec-controls-structure\",\"children\":[]},{\"level\":3,\"title\":\"InSpec Results\",\"slug\":\"inspec-results\",\"link\":\"#inspec-results\",\"children\":[]},{\"level\":3,\"title\":\"Tooling and Reporting\",\"slug\":\"tooling-and-reporting\",\"link\":\"#tooling-and-reporting\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.13,\"words\":639},\"filePathRelative\":\"courses/beginner/02.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
