export const data = JSON.parse("{\"key\":\"v-259cb169\",\"path\":\"/courses/beginner/03.html\",\"title\":\"3. Study an InSpec Profile - NGINX Example\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":3,\"next\":\"04.md\",\"title\":\"3. Study an InSpec Profile - NGINX Example\",\"author\":\"Aaron Lippold\",\"description\":\"Studying an InSpec profile Let's start by creating a profile that will contain NGINX tests. At your terminal, type: tab InSpec Init Command tab Expected Output Understanding the...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/03.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"3. Study an InSpec Profile - NGINX Example\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Studying an InSpec profile Let's start by creating a profile that will contain NGINX tests. At your terminal, type: tab InSpec Init Command tab Expected Output Understanding the...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"3. Study an InSpec Profile - NGINX Example\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Studying an InSpec profile\",\"slug\":\"studying-an-inspec-profile\",\"link\":\"#studying-an-inspec-profile\",\"children\":[{\"level\":3,\"title\":\"Understanding the profile structure\",\"slug\":\"understanding-the-profile-structure\",\"link\":\"#understanding-the-profile-structure\",\"children\":[]},{\"level\":3,\"title\":\"Understand a control's structure\",\"slug\":\"understand-a-control-s-structure\",\"link\":\"#understand-a-control-s-structure\",\"children\":[]},{\"level\":3,\"title\":\"Understand a describe block's structure\",\"slug\":\"understand-a-describe-block-s-structure\",\"link\":\"#understand-a-describe-block-s-structure\",\"children\":[]},{\"level\":3,\"title\":\"Comprehension Check!\",\"slug\":\"comprehension-check\",\"link\":\"#comprehension-check\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.67,\"words\":1101},\"filePathRelative\":\"courses/beginner/03.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
