export const data = JSON.parse("{\"key\":\"v-27518a08\",\"path\":\"/courses/beginner/04.html\",\"title\":\"4. How to Get Started - InSpec Commands & Docs\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":4,\"next\":\"05.md\",\"title\":\"4. How to Get Started - InSpec Commands & Docs\",\"author\":\"Aaron Lippold\",\"description\":\"InSpec Commands and Documentation Before we test our NGINX configuration, let's take a look at the InSpec commands and documentation we can use to write tests. How to Run InSpec...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/04.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"4. How to Get Started - InSpec Commands & Docs\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"InSpec Commands and Documentation Before we test our NGINX configuration, let's take a look at the InSpec commands and documentation we can use to write tests. How to Run InSpec...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"4. How to Get Started - InSpec Commands & Docs\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"InSpec Commands and Documentation\",\"slug\":\"inspec-commands-and-documentation\",\"link\":\"#inspec-commands-and-documentation\",\"children\":[{\"level\":3,\"title\":\"How to Run InSpec\",\"slug\":\"how-to-run-inspec\",\"link\":\"#how-to-run-inspec\",\"children\":[]},{\"level\":3,\"title\":\"How to Write InSpec\",\"slug\":\"how-to-write-inspec\",\"link\":\"#how-to-write-inspec\",\"children\":[]},{\"level\":3,\"title\":\"The InSpec shell\",\"slug\":\"the-inspec-shell\",\"link\":\"#the-inspec-shell\",\"children\":[]},{\"level\":3,\"title\":\"Entering the InSpec shell\",\"slug\":\"entering-the-inspec-shell\",\"link\":\"#entering-the-inspec-shell\",\"children\":[]},{\"level\":3,\"title\":\"Using the InSpec Shell\",\"slug\":\"using-the-inspec-shell\",\"link\":\"#using-the-inspec-shell\",\"children\":[]},{\"level\":3,\"title\":\"Exploring Resources\",\"slug\":\"exploring-resources\",\"link\":\"#exploring-resources\",\"children\":[]}]}],\"readingTime\":{\"minutes\":7.37,\"words\":2212},\"filePathRelative\":\"courses/beginner/04.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
