export const data = JSON.parse("{\"key\":\"v-290662a7\",\"path\":\"/courses/beginner/05.html\",\"title\":\"5. Writing InSpec Controls\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":5,\"next\":\"06.md\",\"title\":\"5. Writing InSpec Controls\",\"author\":\"Aaron Lippold\",\"description\":\"Writing InSpec Controls Let's work through some example requirements to write InSpec controls. Security & Configuration Requirements We write InSpec controls to test some target...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/05.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"5. Writing InSpec Controls\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Writing InSpec Controls Let's work through some example requirements to write InSpec controls. Security & Configuration Requirements We write InSpec controls to test some target...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"5. Writing InSpec Controls\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Writing InSpec Controls\",\"slug\":\"writing-inspec-controls\",\"link\":\"#writing-inspec-controls\",\"children\":[{\"level\":3,\"title\":\"Security & Configuration Requirements\",\"slug\":\"security-configuration-requirements\",\"link\":\"#security-configuration-requirements\",\"children\":[]},{\"level\":3,\"title\":\"Requirement (1) - NGINX Version\",\"slug\":\"requirement-1-nginx-version\",\"link\":\"#requirement-1-nginx-version\",\"children\":[]},{\"level\":3,\"title\":\"Requirement (2) - NGINX Modules are Installed\",\"slug\":\"requirement-2-nginx-modules-are-installed\",\"link\":\"#requirement-2-nginx-modules-are-installed\",\"children\":[]},{\"level\":3,\"title\":\"Requirement (3) - The nginx_conf file\",\"slug\":\"requirement-3-the-nginx-conf-file\",\"link\":\"#requirement-3-the-nginx-conf-file\",\"children\":[]},{\"level\":3,\"title\":\"Requirement (4) - Permission on the nginx_conf file\",\"slug\":\"requirement-4-permission-on-the-nginx-conf-file\",\"link\":\"#requirement-4-permission-on-the-nginx-conf-file\",\"children\":[]},{\"level\":3,\"title\":\"Requirement (5) - NGINX shell access\",\"slug\":\"requirement-5-nginx-shell-access\",\"link\":\"#requirement-5-nginx-shell-access\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.11,\"words\":1532},\"filePathRelative\":\"courses/beginner/05.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
