export const data = JSON.parse("{\"key\":\"v-2c7013e5\",\"path\":\"/courses/beginner/07.html\",\"title\":\"7. InSpec Control Enhancements\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":7,\"next\":\"08.md\",\"title\":\"7. InSpec Control Enhancements\",\"author\":\"Aaron Lippold\",\"description\":\"InSpec Control Enhancements You should have the basic idea of how an InSpec test is written and how to leverage InSpec's built-in features to help you write tests quickly and ea...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/07.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"7. InSpec Control Enhancements\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"InSpec Control Enhancements You should have the basic idea of how an InSpec test is written and how to leverage InSpec's built-in features to help you write tests quickly and ea...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"7. InSpec Control Enhancements\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"InSpec Control Enhancements\",\"slug\":\"inspec-control-enhancements\",\"link\":\"#inspec-control-enhancements\",\"children\":[{\"level\":3,\"title\":\"RSpec\",\"slug\":\"rspec\",\"link\":\"#rspec\",\"children\":[]},{\"level\":3,\"title\":\"RSpec Explicit Subject\",\"slug\":\"rspec-explicit-subject\",\"link\":\"#rspec-explicit-subject\",\"children\":[]},{\"level\":3,\"title\":\"The should vs. expect syntax\",\"slug\":\"the-should-vs-expect-syntax\",\"link\":\"#the-should-vs-expect-syntax\",\"children\":[]},{\"level\":3,\"title\":\"expect syntax with a failure message\",\"slug\":\"expect-syntax-with-a-failure-message\",\"link\":\"#expect-syntax-with-a-failure-message\",\"children\":[]},{\"level\":3,\"title\":\"Expect syntax and Password Hashes\",\"slug\":\"expect-syntax-and-password-hashes\",\"link\":\"#expect-syntax-and-password-hashes\",\"children\":[]},{\"level\":3,\"title\":\"Using Multiple Resources For One Test\",\"slug\":\"using-multiple-resources-for-one-test\",\"link\":\"#using-multiple-resources-for-one-test\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.25,\"words\":1874},\"filePathRelative\":\"courses/beginner/07.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
