export const data = JSON.parse("{\"key\":\"v-556462cd\",\"path\":\"/courses/beginner/10.html\",\"title\":\"10. Profile Dependencies (Overlays)\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":10,\"next\":\"11.md\",\"title\":\"10. Profile Dependencies (Overlays)\",\"author\":\"Aaron Lippold\",\"headerDepth\":3,\"description\":\"Profile Dependencies (Overlays) In addition to its own controls, an InSpec profile can leverage controls from one or more other InSpec profiles. When a profile depends on contro...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/10.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"10. Profile Dependencies (Overlays)\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Profile Dependencies (Overlays) In addition to its own controls, an InSpec profile can leverage controls from one or more other InSpec profiles. When a profile depends on contro...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"10. Profile Dependencies (Overlays)\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Profile Dependencies (Overlays)\",\"slug\":\"profile-dependencies-overlays\",\"link\":\"#profile-dependencies-overlays\",\"children\":[{\"level\":3,\"title\":\"Creating the Overlay\",\"slug\":\"creating-the-overlay\",\"link\":\"#creating-the-overlay\",\"children\":[]},{\"level\":3,\"title\":\"Defining the Profile Dependency\",\"slug\":\"defining-the-profile-dependency\",\"link\":\"#defining-the-profile-dependency\",\"children\":[]},{\"level\":3,\"title\":\"Including All Controls\",\"slug\":\"including-all-controls\",\"link\":\"#including-all-controls\",\"children\":[]},{\"level\":3,\"title\":\"Skipping a Control\",\"slug\":\"skipping-a-control\",\"link\":\"#skipping-a-control\",\"children\":[]},{\"level\":3,\"title\":\"Selectively Including Controls\",\"slug\":\"selectively-including-controls\",\"link\":\"#selectively-including-controls\",\"children\":[]},{\"level\":3,\"title\":\"Modifying a Control\",\"slug\":\"modifying-a-control\",\"link\":\"#modifying-a-control\",\"children\":[]},{\"level\":3,\"title\":\"Additional Examples\",\"slug\":\"additional-examples\",\"link\":\"#additional-examples\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.04,\"words\":1211},\"filePathRelative\":\"courses/beginner/10.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
