export const data = JSON.parse("{\"key\":\"v-58ce140b\",\"path\":\"/courses/beginner/12.html\",\"title\":\"12. Put it in Practice!\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":12,\"next\":\"13.md\",\"title\":\"12. Put it in Practice!\",\"author\":\"Aaron Lippold\",\"headerDepth\":3,\"description\":\"Getting Started on the RHEL8 Baseline Let's practice writing a few 'real' controls using a security guidance document. The Steps to write an InSpec Control 1. Read the Control -...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/beginner/12.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"12. Put it in Practice!\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Getting Started on the RHEL8 Baseline Let's practice writing a few 'real' controls using a security guidance document. The Steps to write an InSpec Control 1. Read the Control -...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"12. Put it in Practice!\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Getting Started on the RHEL8 Baseline\",\"slug\":\"getting-started-on-the-rhel8-baseline\",\"link\":\"#getting-started-on-the-rhel8-baseline\",\"children\":[{\"level\":3,\"title\":\"Example Control Using login_defs Resource:\",\"slug\":\"example-control-using-login-defs-resource\",\"link\":\"#example-control-using-login-defs-resource\",\"children\":[]},{\"level\":3,\"title\":\"Controls We Will Demonstrate\",\"slug\":\"controls-we-will-demonstrate\",\"link\":\"#controls-we-will-demonstrate\",\"children\":[]},{\"level\":3,\"title\":\"Suggested Level 1 Controls\",\"slug\":\"suggested-level-1-controls\",\"link\":\"#suggested-level-1-controls\",\"children\":[]},{\"level\":3,\"title\":\"Suggested Level 2 Controls\",\"slug\":\"suggested-level-2-controls\",\"link\":\"#suggested-level-2-controls\",\"children\":[]},{\"level\":3,\"title\":\"Suggested InSpec Resources to Review\",\"slug\":\"suggested-inspec-resources-to-review\",\"link\":\"#suggested-inspec-resources-to-review\",\"children\":[]}]},{\"level\":2,\"title\":\"Completed RHEL8 Profile for Reference\",\"slug\":\"completed-rhel8-profile-for-reference\",\"link\":\"#completed-rhel8-profile-for-reference\",\"children\":[]}],\"readingTime\":{\"minutes\":3.69,\"words\":1107},\"filePathRelative\":\"courses/beginner/12.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
