<template><div><h2 id="_3-1-security-technical-implementation-guides" tabindex="-1"><a class="header-anchor" href="#_3-1-security-technical-implementation-guides" aria-hidden="true">#</a> 3.1 Security Technical Implementation Guides</h2>
<p>A <strong>Security Technical Implementation Guide (STIG)</strong> is a set of requirements imposed by the US Department of Defense and implementation instructions for those requirements that are specific to a paticular software component. The components can be any piece of technology that needs a secure configuration -- operating systems, webservers, application runtimes, routers, and so on.</p>
<p>STIGs are published by the Defense Information Systems Agency (DISA), but they're usually written by software vendors, which naturally have the most domain knowledge about how to secure their products. DISA then peer reviews the vendor's draft content to ensure it meets its rigorous standards. We'll describe the process for working with DISA to formally publish a STIG later on.</p>
<p>STIGs are also expected to stay up-to-date alongside the software component they describe. STIGs must be updated by the authors and released any time there is a serious change in the software component the STIG describes. Complicated STIGs for widely-used and often-updated components may be updated multiple times a year.</p>
<div class="hint-container note">
<p class="hint-container-title">Are STIGs Familiar?</p>
<p>Have you ever been required to configure an application or system to STIG-standard before?</p>
</div>
<h2 id="_3-2-security-requirements-guides" tabindex="-1"><a class="header-anchor" href="#_3-2-security-requirements-guides" aria-hidden="true">#</a> 3.2 Security Requirements Guides</h2>
<p>STIGs are created based off of high-level, general guidance documents called <strong>Security Requirements Guides (SRGs)</strong>, also published by DISA. SRGs describe DOD-selected security requirements for entire categories of software components, and all STIG requirements are essentially sets of instructions for how to get a particular component to comply with a general SRG (or even a set of SRGs, for complex systems). STIGs are instructions for security that can be followed even by people who are not experts in the technology in question.</p>
<div class="hint-container note">
<p class="hint-container-title">How much STIG are we talking?</p>
<p>STIGs can include hundreds of individual requirements depending on the complexity of the system being configured. At time of writing, the Windows Server 2019 STIG included 303 controls.</p>
<p>We need a way to track and manage all of these easily!</p>
</div>
<h3 id="_3-2-1-srgs-and-stigs-example" tabindex="-1"><a class="header-anchor" href="#_3-2-1-srgs-and-stigs-example" aria-hidden="true">#</a> 3.2.1 SRGs and STIGs - Example</h3>
<p>For example, there is an SRG that covers operating systems in general (the aptly-named &quot;General Purpose Operating System Security Requirements Guide&quot;). That piece of guidance is full of requirements for an operating system -- <em>any</em> operating system -- to be considered reasonably secure. There is a requirement in that SRG (SRG ID: SRG-OS-000021-GPOS-00005) which states that &quot;The operating system must enforce the limit of three consecutive invalid logon attempts by a user during a 15-minute time period.&quot;</p>
<p>This requirement is saying that an attacker shouldn't be able to brute force a user's password by throwing a high number of guesses at the system. Simple enough, right?</p>
<p>However, this guidance isn't particularly useful unless we know how to <strong>implement it</strong> on a particular operating system. That's where the STIG comes in. The STIG for, say, Red Hat 8 (&quot;Red Hat Enterprise Linux 8 STIG&quot;) has its own requirement for limiting consecutive logon attempts (Rule ID: SV-230334r627750_rule) that cites the relevant SRG IDs that it satisfies. That STIG rule tells us <em>exactly how to configure Red Hat to satisfy this requirement</em>, down to which configuration files we need to edit.</p>
<p>You can think of the process of STIG authorship as <em>distilling</em> the high-level, general requirements of an SRG into a checklist that anybody can follow to lock down their component.</p>
<figure><img src="@source/assets/img/SRGvsSTIG.png" alt="Tailoring SRGs into STIGs" tabindex="0" loading="lazy"><figcaption>Tailoring SRGs into STIGs</figcaption></figure>
<p>STIGs are ideally created by a team of subject matter experts on a particular piece of software, all of whom work together to close the gap between the SRG and their shiny new STIG.</p>
<h2 id="_3-3-where-do-all-the-requirements-come-from-anyway" tabindex="-1"><a class="header-anchor" href="#_3-3-where-do-all-the-requirements-come-from-anyway" aria-hidden="true">#</a> 3.3 Where Do All The Requirements Come From, Anyway?</h2>
<p>Published directives from the DOD's Chief Information Officer (DOD CIO) describe the overall Risk Management Framework for DOD Systems (DOD RMF). The DOD RMF requires all information systems across the DOD to be categorized according to how much risk they represent to the organization if compromised. It also requires system owners to select controls from the National Institute of Standards and Technology's (NIST) security control families.</p>
<div class="hint-container note">
<p class="hint-container-title">NIST Control Families</p>
<p>You may be familiar with the control families from <a href="https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final" target="_blank" rel="noopener noreferrer">NIST Special Publication 800-53<ExternalLinkIcon/></a>, because almost all US Government agencies (and quite a few companies) use them as the authoritative list that defines what security controls are.</p>
</div>
<p>To speed up the process of control selection, DISA created and published the <strong>Control Correlation Identifiers (CCIs)</strong>, which describe <em>actions that can be taken</em> to cover the NIST security control families. CCIs are a bridge between the extremely high-level policy  documents that govern the whole DOD and the low-level documents (i.e. STIGs) that actually tell people how to implement that policy.</p>
<p>DISA also publishes the SRGs, which describe <em>subsets</em> of CCIs that apply to general categories of information systems. This means that individual system owners do not have to figure out on their own which control families need to be covered for their system; they can instead say &quot;I am deploying a router, so I must cover the requirements selected in the Router SRG.&quot;</p>
<p>As described before, an SRG can then be tailored into STIGs that give security guidance for individual pieces of software. The full chain of requirements to implementation therefore looks like this:</p>
<figure><img src="@source/assets/img/STIGSources.png" alt="Process Flow of DOD Requirements Assembly Into SRGs/STIGs" tabindex="0" loading="lazy"><figcaption>Process Flow of DOD Requirements Assembly Into SRGs/STIGs</figcaption></figure>
<h3 id="_3-3-1-now-for-the-good-news" tabindex="-1"><a class="header-anchor" href="#_3-3-1-now-for-the-good-news" aria-hidden="true">#</a> 3.3.1 Now For The Good News</h3>
<p>The good news is that you, the STIG content author, don't have to worry about SRGs or control selections all that much; the whole point of all the good work that DISA has done is that most of these mappings have been done for you. You are responsible for the last leg of the journey -- you know your requirements from the SRG, and now you need to figure out how to implement them as a configuration baseline.</p>
</div></template>


