export const data = JSON.parse("{\"key\":\"v-7765bc4c\",\"path\":\"/courses/guidance/06.html\",\"title\":\"6. Components Of a Vulcan Project\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":6,\"next\":\"07.md\",\"title\":\"6. Components Of a Vulcan Project\",\"author\":\"Will Dower\",\"headerDepth\":3,\"description\":\"6.1 Components We have our project created and have allowed access to everyone who needs it. Now let's create ourselves a Component. 6.1.1 Consider Your Component's Requirements...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/guidance/06.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"6. Components Of a Vulcan Project\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"6.1 Components We have our project created and have allowed access to everyone who needs it. Now let's create ourselves a Component. 6.1.1 Consider Your Component's Requirements...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Will Dower\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"6. Components Of a Vulcan Project\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Will Dower\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"6.1 Components\",\"slug\":\"_6-1-components\",\"link\":\"#_6-1-components\",\"children\":[{\"level\":3,\"title\":\"6.1.1 Consider Your Component's Requirements\",\"slug\":\"_6-1-1-consider-your-component-s-requirements\",\"link\":\"#_6-1-1-consider-your-component-s-requirements\",\"children\":[]},{\"level\":3,\"title\":\"6.1.2 Choosing a Foundation\",\"slug\":\"_6-1-2-choosing-a-foundation\",\"link\":\"#_6-1-2-choosing-a-foundation\",\"children\":[]}]},{\"level\":2,\"title\":\"6.2 Creating a Component for Your Project\",\"slug\":\"_6-2-creating-a-component-for-your-project\",\"link\":\"#_6-2-creating-a-component-for-your-project\",\"children\":[]},{\"level\":2,\"title\":\"6.3 Examining the Component\",\"slug\":\"_6-3-examining-the-component\",\"link\":\"#_6-3-examining-the-component\",\"children\":[{\"level\":3,\"title\":\"6.3.1 Layout of the Component View\",\"slug\":\"_6-3-1-layout-of-the-component-view\",\"link\":\"#_6-3-1-layout-of-the-component-view\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.31,\"words\":694},\"filePathRelative\":\"courses/guidance/06.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
