export const data = JSON.parse("{\"key\":\"v-7acf6d8a\",\"path\":\"/courses/guidance/08.html\",\"title\":\"8. Check and Fix\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":8,\"next\":\"09.md\",\"title\":\"8. Check and Fix\",\"author\":\"Will Dower\",\"headerDepth\":3,\"description\":\"8.1 Check and Fix Let's go back to our requirement for earlier that we said was \\\"Applicable - Configurable.\\\" It's time to fill it out completely. The Check and Fix fields are th...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/guidance/08.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"8. Check and Fix\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"8.1 Check and Fix Let's go back to our requirement for earlier that we said was \\\"Applicable - Configurable.\\\" It's time to fill it out completely. The Check and Fix fields are th...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"8. Check and Fix\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Will Dower\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"8. Check and Fix\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Will Dower\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"8.1 Check and Fix\",\"slug\":\"_8-1-check-and-fix\",\"link\":\"#_8-1-check-and-fix\",\"children\":[]},{\"level\":2,\"title\":\"8.2 Check\",\"slug\":\"_8-2-check\",\"link\":\"#_8-2-check\",\"children\":[{\"level\":3,\"title\":\"8.2.1 Check Writing Style\",\"slug\":\"_8-2-1-check-writing-style\",\"link\":\"#_8-2-1-check-writing-style\",\"children\":[]}]},{\"level\":2,\"title\":\"8.3 Fix\",\"slug\":\"_8-3-fix\",\"link\":\"#_8-3-fix\",\"children\":[]},{\"level\":2,\"title\":\"8.3.1 Fix Writing Style\",\"slug\":\"_8-3-1-fix-writing-style\",\"link\":\"#_8-3-1-fix-writing-style\",\"children\":[]},{\"level\":2,\"title\":\"8.4 Completing Our Requirement\",\"slug\":\"_8-4-completing-our-requirement\",\"link\":\"#_8-4-completing-our-requirement\",\"children\":[{\"level\":3,\"title\":\"8.4.1 Using Other STIGs as Reference\",\"slug\":\"_8-4-1-using-other-stigs-as-reference\",\"link\":\"#_8-4-1-using-other-stigs-as-reference\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.35,\"words\":1306},\"filePathRelative\":\"courses/guidance/08.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
