export const data = JSON.parse("{\"key\":\"v-7c844629\",\"path\":\"/courses/guidance/09.html\",\"title\":\"9. Automated InSpec Testing\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":9,\"next\":\"10.md\",\"title\":\"9. Automated InSpec Testing\",\"author\":\"Sumaa Sayed\",\"headerDepth\":3,\"description\":\"9.1 Automated Validation Tests Now that we have written up some Check and Fix text, it's time to use one of Vulcan's other features -- the InSpec code pane. We've already used V...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/guidance/09.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"9. Automated InSpec Testing\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"9.1 Automated Validation Tests Now that we have written up some Check and Fix text, it's time to use one of Vulcan's other features -- the InSpec code pane. We've already used V...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"9. Automated InSpec Testing\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Sumaa Sayed\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"9. Automated InSpec Testing\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Sumaa Sayed\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"9.1 Automated Validation Tests\",\"slug\":\"_9-1-automated-validation-tests\",\"link\":\"#_9-1-automated-validation-tests\",\"children\":[{\"level\":3,\"title\":\"9.1.1 The InSpec Control Body\",\"slug\":\"_9-1-1-the-inspec-control-body\",\"link\":\"#_9-1-1-the-inspec-control-body\",\"children\":[]},{\"level\":3,\"title\":\"9.1.2 Why am I writing test code inside Vulcan?\",\"slug\":\"_9-1-2-why-am-i-writing-test-code-inside-vulcan\",\"link\":\"#_9-1-2-why-am-i-writing-test-code-inside-vulcan\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.21,\"words\":663},\"filePathRelative\":\"courses/guidance/09.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
