export const data = JSON.parse("{\"key\":\"v-b878871c\",\"path\":\"/courses/guidance/11.html\",\"title\":\"11. Exporting Your Content\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":11,\"next\":\"12.md\",\"title\":\"11. Exporting Your Content\",\"author\":\"Will Dower\",\"headerDepth\":3,\"description\":\"11.1 Exporting Your Content At this point, we have tailored two requirements from the original SRG into STIG-ready content, and discussed how to peer review them. Let's discuss ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/guidance/11.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"11. Exporting Your Content\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"11.1 Exporting Your Content At this point, we have tailored two requirements from the original SRG into STIG-ready content, and discussed how to peer review them. Let's discuss ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"11. Exporting Your Content\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Will Dower\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"11. Exporting Your Content\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Will Dower\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"11.1 Exporting Your Content\",\"slug\":\"_11-1-exporting-your-content\",\"link\":\"#_11-1-exporting-your-content\",\"children\":[]},{\"level\":2,\"title\":\"11.2 Exporting the Guidance Document\",\"slug\":\"_11-2-exporting-the-guidance-document\",\"link\":\"#_11-2-exporting-the-guidance-document\",\"children\":[{\"level\":3,\"title\":\"11.2.1 Notes on Releasing\",\"slug\":\"_11-2-1-notes-on-releasing\",\"link\":\"#_11-2-1-notes-on-releasing\",\"children\":[]},{\"level\":3,\"title\":\"11.2.2 Notes on Exporting\",\"slug\":\"_11-2-2-notes-on-exporting\",\"link\":\"#_11-2-2-notes-on-exporting\",\"children\":[]}]},{\"level\":2,\"title\":\"11.3 Diff Viewer\",\"slug\":\"_11-3-diff-viewer\",\"link\":\"#_11-3-diff-viewer\",\"children\":[{\"level\":3,\"title\":\"11.3.1 Creating a Different Component\",\"slug\":\"_11-3-1-creating-a-different-component\",\"link\":\"#_11-3-1-creating-a-different-component\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.78,\"words\":834},\"filePathRelative\":\"courses/guidance/11.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
