<template><div><h2 id="_13-1-next-steps" tabindex="-1"><a class="header-anchor" href="#_13-1-next-steps" aria-hidden="true">#</a> 13.1 Next Steps</h2>
<h3 id="_13-1-1-take-the-class-survey" tabindex="-1"><a class="header-anchor" href="#_13-1-1-take-the-class-survey" aria-hidden="true">#</a> 13.1.1 Take the Class Survey</h3>
<p>Take our question <a href="https://forms.office.com/g/JPUWUVjXes" target="_blank" rel="noopener noreferrer">survey<ExternalLinkIcon/></a> to give feedback to fuel class improvement.</p>
<h3 id="_13-1-2-take-other-saf-training-like-the-security-automation-developer-classes-or-the-saf-user-class" tabindex="-1"><a class="header-anchor" href="#_13-1-2-take-other-saf-training-like-the-security-automation-developer-classes-or-the-saf-user-class" aria-hidden="true">#</a> 13.1.2 Take other SAF training like the Security Automation Developer Classes or the SAF User Class</h3>
<p>This class is one of a set of security automation content offered by the MITRE SAF(c) team. If you found this content interesting and you want to learn more about more technical topics like writing complete InSpec profiles of your own, we encourage you to check out the <RouterLink to="/courses/beginner/">Beginner</RouterLink> and <RouterLink to="/courses/advanced/">Advanced</RouterLink> Security Automation Developer Class (shown in the table of contents on the left). If you have not taken the User Class and want to put the SAF in action, take a look at the <RouterLink to="/courses/user/">SAF User Class</RouterLink>.</p>
<h3 id="_13-1-3-check-out-the-rest-of-mitre-saf-c-s-content" tabindex="-1"><a class="header-anchor" href="#_13-1-3-check-out-the-rest-of-mitre-saf-c-s-content" aria-hidden="true">#</a> 13.1.3 Check Out the Rest of MITRE SAF(c)'s Content</h3>
<p>MITRE SAF(c) is a large collection of tools and techniques for security automation in addition to those discussed in this class. You can find utilities and libraries to support any step of the software development lifecycle by browsing our offerings at <a href="https://saf.mitre.org" target="_blank" rel="noopener noreferrer">saf.mitre.org<ExternalLinkIcon/></a>. Note that everything offered by MITRE SAF(c) is open-source and available to use free of charge. You can also reference all of the resources listed from the class on the <RouterLink to="/resources/">Resources Page</RouterLink></p>
<h3 id="_13-1-4-contact-us" tabindex="-1"><a class="header-anchor" href="#_13-1-4-contact-us" aria-hidden="true">#</a> 13.1.4 Contact Us</h3>
<p>The MITRE SAF(c) team can be contacted at <a href="mailto:saf@groups.mitre.org">saf@groups.mitre.org</a>. We support U.S. government sponsors in developing new tools for the Framework and in implementing the existing ones in DevSecOps pipelines. If you have a question about how you can use any of the content you saw in this class in your own environment, we'd be happy to help.</p>
</div></template>


