export const data = JSON.parse("{\"key\":\"v-4f4ac476\",\"path\":\"/installation/WindowsInstall.html\",\"title\":\"Installing InSpec on Windows\",\"lang\":\"en-US\",\"frontmatter\":{\"index\":true,\"icon\":\"page\",\"title\":\"Installing InSpec on Windows\",\"author\":\"Aaron Lippold\",\"prev\":\"./\",\"description\":\"Install Ruby Go to https://rubyinstaller.org/downloads/ (https://rubyinstaller.org/downloads/) and download and install the newest ruby that corresponds with your operating syst...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/installation/WindowsInstall.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Installing InSpec on Windows\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Install Ruby Go to https://rubyinstaller.org/downloads/ (https://rubyinstaller.org/downloads/) and download and install the newest ruby that corresponds with your operating syst...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Installing InSpec on Windows\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Install Ruby\",\"slug\":\"install-ruby\",\"link\":\"#install-ruby\",\"children\":[]},{\"level\":2,\"title\":\"Install InSpec\",\"slug\":\"install-inspec\",\"link\":\"#install-inspec\",\"children\":[{\"level\":3,\"title\":\"Option 1 (Download as a package)\",\"slug\":\"option-1-download-as-a-package\",\"link\":\"#option-1-download-as-a-package\",\"children\":[]},{\"level\":3,\"title\":\"Option 2 (Download as a ruby gem)\",\"slug\":\"option-2-download-as-a-ruby-gem\",\"link\":\"#option-2-download-as-a-ruby-gem\",\"children\":[]},{\"level\":3,\"title\":\"Option 3 (windows only)\",\"slug\":\"option-3-windows-only\",\"link\":\"#option-3-windows-only\",\"children\":[]}]},{\"level\":2,\"title\":\"Download additional required gems\",\"slug\":\"download-additional-required-gems\",\"link\":\"#download-additional-required-gems\",\"children\":[]},{\"level\":2,\"title\":\"After Install\",\"slug\":\"after-install\",\"link\":\"#after-install\",\"children\":[]}],\"readingTime\":{\"minutes\":0.93,\"words\":280},\"filePathRelative\":\"installation/WindowsInstall.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
