export const data = JSON.parse("{\"key\":\"v-30844539\",\"path\":\"/courses/advanced/03.html\",\"title\":\"3. Practice the Fundamentals\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":3,\"next\":\"04.md\",\"title\":\"3. Practice the Fundamentals\",\"author\":\"Aaron Lippold\",\"headerDepth\":3,\"description\":\"Revisiting the NGINX Web Server InSpec Profile In the beginner class (../beginner/05.md), we wrote and ran an InSpec profile against a test container. We then generated a report...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/advanced/03.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"3. Practice the Fundamentals\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Revisiting the NGINX Web Server InSpec Profile In the beginner class (../beginner/05.md), we wrote and ran an InSpec profile against a test container. We then generated a report...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"3. Practice the Fundamentals\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Revisiting the NGINX Web Server InSpec Profile\",\"slug\":\"revisiting-the-nginx-web-server-inspec-profile\",\"link\":\"#revisiting-the-nginx-web-server-inspec-profile\",\"children\":[{\"level\":3,\"title\":\"The Target\",\"slug\":\"the-target\",\"link\":\"#the-target\",\"children\":[]},{\"level\":3,\"title\":\"The Requirements\",\"slug\":\"the-requirements\",\"link\":\"#the-requirements\",\"children\":[]},{\"level\":3,\"title\":\"The Controls\",\"slug\":\"the-controls\",\"link\":\"#the-controls\",\"children\":[]},{\"level\":3,\"title\":\"Running the Controls\",\"slug\":\"running-the-controls\",\"link\":\"#running-the-controls\",\"children\":[]},{\"level\":3,\"title\":\"Reporting Results\",\"slug\":\"reporting-results\",\"link\":\"#reporting-results\",\"children\":[]},{\"level\":3,\"title\":\"Visualizing Results\",\"slug\":\"visualizing-results\",\"link\":\"#visualizing-results\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.95,\"words\":885},\"filePathRelative\":\"courses/advanced/03.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
