export const data = JSON.parse("{\"key\":\"v-35a2cf16\",\"path\":\"/courses/advanced/06.html\",\"title\":\"6. Create a Custom Resource - The Docker Example\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":6,\"next\":\"07.md\",\"title\":\"6. Create a Custom Resource - The Docker Example\",\"author\":\"Aaron Lippold\",\"headerDepth\":3,\"description\":\"Custom Resource - Docker Now let's try a more complicated example. Let's say we want to create a resource that can parse a docker-compose file. Create new profile and setup Dock...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/advanced/06.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"6. Create a Custom Resource - The Docker Example\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Custom Resource - Docker Now let's try a more complicated example. Let's say we want to create a resource that can parse a docker-compose file. Create new profile and setup Dock...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"6. Create a Custom Resource - The Docker Example\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Custom Resource - Docker\",\"slug\":\"custom-resource-docker\",\"link\":\"#custom-resource-docker\",\"children\":[{\"level\":3,\"title\":\"Create new profile and setup Docker files\",\"slug\":\"create-new-profile-and-setup-docker-files\",\"link\":\"#create-new-profile-and-setup-docker-files\",\"children\":[]},{\"level\":3,\"title\":\"Develop controls to test/run profile\",\"slug\":\"develop-controls-to-test-run-profile\",\"link\":\"#develop-controls-to-test-run-profile\",\"children\":[]},{\"level\":3,\"title\":\"Rewrite test to utilize a new resource\",\"slug\":\"rewrite-test-to-utilize-a-new-resource\",\"link\":\"#rewrite-test-to-utilize-a-new-resource\",\"children\":[]},{\"level\":3,\"title\":\"Develop the Docker resource\",\"slug\":\"develop-the-docker-resource\",\"link\":\"#develop-the-docker-resource\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.56,\"words\":1968},\"filePathRelative\":\"courses/advanced/06.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
