<template><div><h2 id="next-steps" tabindex="-1"><a class="header-anchor" href="#next-steps" aria-hidden="true">#</a> Next Steps</h2>
<h3 id="take-the-class-survey" tabindex="-1"><a class="header-anchor" href="#take-the-class-survey" aria-hidden="true">#</a> Take the Class Survey</h3>
<p>Take our brief <a href="https://forms.office.com/g/W2xtcV2frW" target="_blank" rel="noopener noreferrer">survey<ExternalLinkIcon/></a> to give feedback to fuel class improvement.</p>
<h3 id="save-your-work-on-github" tabindex="-1"><a class="header-anchor" href="#save-your-work-on-github" aria-hidden="true">#</a> Save your work on GitHub</h3>
<p>If you want to save your work in your remote repository in GitHub, you need to use Git commands. You can reference a <a href="https://education.github.com/git-cheat-sheet-education.pdf" target="_blank" rel="noopener noreferrer">Git cheat sheet<ExternalLinkIcon/></a> or checkout <a href="https://learngitbranching.js.org/" target="_blank" rel="noopener noreferrer">this Git tutorial<ExternalLinkIcon/></a>.</p>
<h3 id="reference-other-class-content" tabindex="-1"><a class="header-anchor" href="#reference-other-class-content" aria-hidden="true">#</a> Reference other class content</h3>
<p>This class is one of a set of security automation content offered by the MITRE SAF(c) team. If you found this content interesting and you want to learn more, we encourage you to go back to the User Class or Beginner Security Automation Developer Class (shown in the table of contents on the left).</p>
<h3 id="check-out-the-rest-of-mitre-saf-c-s-content" tabindex="-1"><a class="header-anchor" href="#check-out-the-rest-of-mitre-saf-c-s-content" aria-hidden="true">#</a> Check Out the Rest of MITRE SAF(c)'s Content</h3>
<p>MITRE SAF(c) is a large collection of tools and techniques for security automation in addition to those discussed in this class. You can find utilities and libraries to support any step of the software development lifecycle by browsing our offerings at <a href="https://saf.mitre.org" target="_blank" rel="noopener noreferrer">saf.mitre.org<ExternalLinkIcon/></a>. Note that everything offered by MITRE SAF(c) is open-source and available to use free of charge. You can also reference all of the resources listed from the class on the <RouterLink to="/resources/">Resources Page</RouterLink></p>
<h3 id="contact-us" tabindex="-1"><a class="header-anchor" href="#contact-us" aria-hidden="true">#</a> Contact Us</h3>
<p>The MITRE SAF(c) team can be contacted at <a href="mailto:saf@groups.mitre.org">saf@groups.mitre.org</a>. We support U.S. government sponsors in developing new tools for the Framework and in implementing the existing ones in DevSecOps pipelines. If you have a question about how you can use any of the content you saw in this class in your own environment, we'd be happy to help.</p>
</div></template>


