export const data = JSON.parse("{\"key\":\"v-32f5f052\",\"path\":\"/courses/advanced/Appendix%20A%20-%20Writing%20Plural%20Resources.html\",\"title\":\"Appendix A - Writing Plural Resources\",\"lang\":\"en-US\",\"frontmatter\":{\"order\":14,\"title\":\"Appendix A - Writing Plural Resources\",\"author\":\"Aaron Lippold\",\"headerDepth\":3,\"description\":\"10. Plural Resources You might have noticed that many InSpec resources have a \\\"plural\\\" version. For example, user has a users counterpart, and package has packages. Plural resou...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/courses/advanced/Appendix%20A%20-%20Writing%20Plural%20Resources.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MITRE SAF Training\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Appendix A - Writing Plural Resources\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"10. Plural Resources You might have noticed that many InSpec resources have a \\\"plural\\\" version. For example, user has a users counterpart, and package has packages. Plural resou...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Aaron Lippold\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Appendix A - Writing Plural Resources\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Aaron Lippold\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"10. Plural Resources\",\"slug\":\"_10-plural-resources\",\"link\":\"#_10-plural-resources\",\"children\":[{\"level\":3,\"title\":\"10.1. Using FilterTable to write a Plural Resource\",\"slug\":\"_10-1-using-filtertable-to-write-a-plural-resource\",\"link\":\"#_10-1-using-filtertable-to-write-a-plural-resource\",\"children\":[]},{\"level\":3,\"title\":\"10.2. FilterTable Hands-On\",\"slug\":\"_10-2-filtertable-hands-on\",\"link\":\"#_10-2-filtertable-hands-on\",\"children\":[]},{\"level\":3,\"title\":\"10.3. Predefined Methods for FilterTable\",\"slug\":\"_10-3-predefined-methods-for-filtertable\",\"link\":\"#_10-3-predefined-methods-for-filtertable\",\"children\":[]},{\"level\":3,\"title\":\"10.4 FilterTable Examples\",\"slug\":\"_10-4-filtertable-examples\",\"link\":\"#_10-4-filtertable-examples\",\"children\":[]}]}],\"readingTime\":{\"minutes\":7.71,\"words\":2312},\"filePathRelative\":\"courses/advanced/Appendix A - Writing Plural Resources.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
